
modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="dankestmod" #mandatory
version="1.16.4-1.0.0" #mandatory

displayName="Dankest Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="This one's for the Bois." #optional

authors="SkilzMastr, Human144, Shot164" #optional

description='''
This mod was made for the Dankest MC Server.
'''


[[dependencies.dankestmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dankestmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
